name: Filtrado de datos de una tabla

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_earnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run command in the vm
        run: |
          echo "Vamos a imprimir una tabla de datos!"
          cat tabladatos.csv
          echo "Filtrado de datos para usuarios hotmail!"
          grep -iv hotmail tabladatos.csv
